services:
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
      - ../secrets
    restart: on-failure

  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
      - ../secrets
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "9000:9000"
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
      - ../secrets
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  inception:
    driver: bridge
